### ISSUE TITLE
大佬写个quicktext的解锁脚本呗

### ISSUE THREAD

**Issue by chengkongyiban** [Marol62926/MarScrpt#1]
一个1.6m大小的文本编辑器，用起来还挺方便。

**Comment by Marol62926** [comment]
这种都是内购的，不是订阅制的，和http catcher一个道理，破解是没有意义的

**Comment by Marol62926** [comment]
> 一个1.6m大小的文本编辑器，用起来还挺方便。

这种都是内购的，不是订阅制的，和http catcher一个道理，破解是没有意义的

**Comment by chengkongyiban** [comment]
> > 一个1.6m大小的文本编辑器，用起来还挺方便。
> 
> 这种都是内购的，不是订阅制的，和http catcher一个道理，破解是没有意义的
感谢解答。谢谢大佬
